repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
    - id: commitizen
    - id: commitizen-branch
      stages:
        - push
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
